import { FieldValue, getFirestore, type DocumentSnapshot } from "firebase-admin/firestore";
import type { DeckSlide } from "../../lib/decks/slide-assignment.ts";
import { WORKSPACE_ROLES, type WorkspaceRole } from "../../lib/workspaces/api-response.ts";
import { authenticateActiveAccount } from "./_shared/authenticated-account.ts";
import { getFirebaseAdminApp } from "./_shared/firebase-admin.ts";

const headers = { "content-type": "application/json; charset=utf-8" };
const DECK_SLIDE_LIMIT = 50;
const json = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status, headers });
const editing = (role: WorkspaceRole) => role !== "viewer";
const role = (value: unknown): value is WorkspaceRole => typeof value === "string" && WORKSPACE_ROLES.includes(value as WorkspaceRole);
function route(request: Request) {
  const url = new URL(request.url);
  const workspaceId = url.searchParams.get("workspaceId")?.trim();
  const deckId = url.searchParams.get("deckId")?.trim();
  const assignmentId = url.searchParams.get("assignmentId")?.trim() || null;
  if (workspaceId && deckId) return { workspaceId, deckId, assignmentId };
  const match = url.pathname.match(/^\/api\/workspaces\/([^/]+)\/decks\/([^/]+)\/slides(?:\/([^/]+))?$/);
  if (!match?.[1] || !match[2]) return null;
  try {
    const pathWorkspaceId = decodeURIComponent(match[1]).trim();
    const pathDeckId = decodeURIComponent(match[2]).trim();
    const pathAssignmentId = match[3] ? decodeURIComponent(match[3]).trim() : null;
    return pathWorkspaceId && pathDeckId ? { workspaceId: pathWorkspaceId, deckId: pathDeckId, assignmentId: pathAssignmentId || null } : null;
  } catch { return null; }
}
function token(request: Request) { const value = request.headers.get("authorization"); return value?.startsWith("Bearer ") ? value.slice(7).trim() : null; }
function read(snapshot: DocumentSnapshot): DeckSlide | null { const slideId = snapshot.get("slideId"), title = snapshot.get("title"), description = snapshot.get("description"), qrCodeId = snapshot.get("qrCodeId") ?? null, qrCodeName = snapshot.get("qrCodeName") ?? null, position = snapshot.get("position"), displayDurationSeconds = snapshot.get("displayDurationSeconds"); return snapshot.exists && snapshot.get("status") === "active" && typeof slideId === "string" && typeof title === "string" && typeof description === "string" && (qrCodeId === null || typeof qrCodeId === "string") && (qrCodeName === null || typeof qrCodeName === "string") && Number.isSafeInteger(position) && (displayDurationSeconds === null || Number.isSafeInteger(displayDurationSeconds)) ? { id: snapshot.id, slideId, title, description, qrCodeId, qrCodeName, position, displayDurationSeconds } : null; }

export default async function deckSlides(request: Request) {
  try {
    const idToken = token(request); if (!idToken) return json({ error: "Authentication required." }, 401);
    const account = await authenticateActiveAccount(idToken); if (!account) return json({ error: "Authentication required." }, 401);
    const currentRoute = route(request); if (!currentRoute) return json({ error: "A workspace and deck are required." }, 400);
    const db = getFirestore(getFirebaseAdminApp()); const workspace = db.doc(`workspaces/${currentRoute.workspaceId}`); const membership = db.doc(`workspaceMemberships/${currentRoute.workspaceId}_${account.uid}`); const deck = workspace.collection("decks").doc(currentRoute.deckId);
    const [workspaceSnapshot, membershipSnapshot, deckSnapshot] = await db.getAll(workspace, membership, deck); const memberRole = membershipSnapshot.get("role");
    if (!workspaceSnapshot.exists || workspaceSnapshot.get("status") !== "active" || !membershipSnapshot.exists || membershipSnapshot.get("status") !== "active" || !role(memberRole) || !deckSnapshot.exists || deckSnapshot.get("status") !== "active") return json({ error: "Workspace access denied." }, 403);
    const assignments = deck.collection("slides");
    if (request.method === "GET" && !currentRoute.assignmentId) { const snapshots = await assignments.orderBy("position").get(); return json({ slides: snapshots.docs.flatMap((item) => { const value = read(item); return value ? [value] : []; }) }); }
    if (!editing(memberRole)) return json({ error: "Editing access required." }, 403);
    if (request.method === "POST" && !currentRoute.assignmentId) { const body: unknown = await request.json().catch(() => null); if (!body || typeof body !== "object" || !("slideId" in body) || typeof body.slideId !== "string" || !body.slideId.trim()) return json({ error: "A slide is required." }, 400); const source = workspace.collection("slides").doc(body.slideId.trim()); const assignment = assignments.doc(); const result = await db.runTransaction(async (transaction) => { const [sourceSnapshot, deckState] = await Promise.all([transaction.get(source), transaction.get(deck)]); if (!sourceSnapshot.exists || sourceSnapshot.get("status") !== "active") return { kind: "missing" as const }; const title = sourceSnapshot.get("title"), description = sourceSnapshot.get("description"), qrCodeId = sourceSnapshot.get("qrCodeId") ?? null, qrCodeName = sourceSnapshot.get("qrCodeName") ?? null, slideCount = deckState.get("slideCount") ?? 0; if (typeof title !== "string" || typeof description !== "string" || (qrCodeId !== null && typeof qrCodeId !== "string") || (qrCodeName !== null && typeof qrCodeName !== "string") || !Number.isSafeInteger(slideCount)) return { kind: "missing" as const }; if (slideCount >= DECK_SLIDE_LIMIT) return { kind: "limit" as const }; const now = FieldValue.serverTimestamp(); transaction.set(assignment, { slideId: source.id, title, description, qrCodeId, qrCodeName, position: slideCount, displayDurationSeconds: null, status: "active", createdAt: now, updatedAt: now }); transaction.update(deck, { slideCount: slideCount + 1, version: (deckState.get("version") ?? 1) + 1, updatedAt: now }); return { kind: "added" as const, slide: { id: assignment.id, slideId: source.id, title, description, qrCodeId, qrCodeName, position: slideCount, displayDurationSeconds: null } satisfies DeckSlide }; }); return result.kind === "added" ? json({ slide: result.slide }, 201) : result.kind === "limit" ? json({ error: `A deck can contain up to ${DECK_SLIDE_LIMIT} slides.` }, 409) : json({ error: "Slide not found." }, 404); }
    if (request.method === "PATCH" && !currentRoute.assignmentId) { const body: unknown = await request.json().catch(() => null); const orderedAssignmentIds = body && typeof body === "object" && "orderedAssignmentIds" in body ? body.orderedAssignmentIds : null; if (!Array.isArray(orderedAssignmentIds) || !orderedAssignmentIds.every((id) => typeof id === "string" && id.trim())) return json({ error: "A complete slide order is required." }, 400); const result = await db.runTransaction(async (transaction) => { const [snapshots, latestDeck] = await Promise.all([transaction.get(assignments.orderBy("position")), transaction.get(deck)]); const active = snapshots.docs.filter((item) => item.get("status") === "active"); const currentIds = new Set(active.map((item) => item.id)); if (orderedAssignmentIds.length !== active.length || new Set(orderedAssignmentIds).size !== active.length || orderedAssignmentIds.some((id) => !currentIds.has(id))) return { kind: "mismatch" as const }; const now = FieldValue.serverTimestamp(); orderedAssignmentIds.forEach((id, position) => transaction.update(assignments.doc(id), { position, updatedAt: now })); transaction.update(deck, { version: (latestDeck.get("version") ?? 1) + 1, updatedAt: now }); return { kind: "updated" as const }; }); return result.kind === "updated" ? json({ ok: true }) : json({ error: "The deck changed. Reload and try again." }, 409); }
    if (request.method === "DELETE" && currentRoute.assignmentId) { const assignment = assignments.doc(currentRoute.assignmentId); const result = await db.runTransaction(async (transaction) => { const [snapshot, latestDeck, snapshots] = await Promise.all([transaction.get(assignment), transaction.get(deck), transaction.get(assignments.orderBy("position"))]); if (!snapshot.exists || snapshot.get("status") !== "active") return { kind: "missing" as const }; const active = snapshots.docs.filter((item) => item.get("status") === "active" && item.id !== assignment.id); const now = FieldValue.serverTimestamp(); transaction.update(assignment, { status: "archived", updatedAt: now }); active.forEach((item, position) => transaction.update(item.ref, { position, updatedAt: now })); transaction.update(deck, { slideCount: active.length, version: (latestDeck.get("version") ?? 1) + 1, updatedAt: now }); return { kind: "removed" as const }; }); return result.kind === "removed" ? json({ ok: true }) : json({ error: "Deck slide not found." }, 404); }
    if (request.method === "PATCH" && currentRoute.assignmentId) { const body: unknown = await request.json().catch(() => null); const duration = body && typeof body === "object" && "displayDurationSeconds" in body ? body.displayDurationSeconds : undefined; if (duration !== null && (!Number.isSafeInteger(duration) || Number(duration) < 1)) return json({ error: "A timing override must be a positive whole number or null." }, 400); const assignment = assignments.doc(currentRoute.assignmentId); await db.runTransaction(async (transaction) => { const [snapshot, latestDeck] = await Promise.all([transaction.get(assignment), transaction.get(deck)]); if (!snapshot.exists || snapshot.get("status") !== "active") throw new Error("Deck slide not found."); const now = FieldValue.serverTimestamp(); transaction.update(assignment, { displayDurationSeconds: duration, updatedAt: now }); transaction.update(deck, { version: (latestDeck.get("version") ?? 1) + 1, updatedAt: now }); }); return json({ ok: true }); }
    return json({ error: "Method not allowed." }, 405);
  } catch (error) { console.error("Deck slide request failed.", error); return json({ error: "Deck slide access is unavailable." }, 503); }
}
