import { FieldValue, getFirestore, type DocumentSnapshot } from "firebase-admin/firestore";
import { decideIconCreation } from "../../lib/icons/creation.ts";
import type { IconSummary } from "../../lib/icons/api-response.ts";
import { WORKSPACE_ROLES, type WorkspaceRole } from "../../lib/workspaces/api-response.ts";
import { authenticateActiveAccount } from "./_shared/authenticated-account.ts";
import { getFirebaseAdminApp } from "./_shared/firebase-admin.ts";
type Account={uid:string}; type Access={role:WorkspaceRole}; type Input={name:string;imageDataUrl:string};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json; charset=utf-8"}});
function route(request:Request){const url=new URL(request.url),query=url.searchParams.get("workspaceId")?.trim();if(query)return query;const match=url.pathname.match(/^\/api\/workspaces\/([^/]+)\/icons$/);try{return match?.[1]?decodeURIComponent(match[1]).trim()||null:null}catch{return null}}
function token(request:Request){const value=request.headers.get("authorization");return value?.startsWith("Bearer ")?value.slice(7).trim()||null:null}
function role(value:unknown):value is WorkspaceRole{return typeof value==="string"&&WORKSPACE_ROLES.includes(value as WorkspaceRole)}
function summary(snapshot:DocumentSnapshot):IconSummary|null{const name=snapshot.get("name"),imageDataUrl=snapshot.get("imageDataUrl");return snapshot.exists&&snapshot.get("status")==="active"&&typeof name==="string"&&typeof imageDataUrl==="string"?{id:snapshot.id,name,imageDataUrl}:null}
export function createIconHandler(deps:{authenticate:(token:string)=>Promise<Account|null>;authorize:(a:Account,w:string)=>Promise<Access|null>;list:(a:Account,w:string)=>Promise<IconSummary[]>;create:(a:Account,w:string,i:Input)=>Promise<{kind:"created";icon:IconSummary}|{kind:"limit";limit:number}>}){return async(request:Request)=>{const idToken=token(request);if(!idToken)return json({error:"Authentication required."},401);const account=await deps.authenticate(idToken);if(!account)return json({error:"Authentication required."},401);const workspaceId=route(request);if(!workspaceId)return json({error:"A workspace is required."},400);const access=await deps.authorize(account,workspaceId);if(!access)return json({error:"Workspace access denied."},403);if(request.method==="GET")return json({icons:await deps.list(account,workspaceId)});if(access.role==="viewer")return json({error:"Editing access required."},403);const body:unknown=await request.json().catch(()=>null);if(request.method!=="POST"||typeof body!=="object"||body===null||!("name"in body)||typeof body.name!=="string"||!("imageDataUrl"in body)||typeof body.imageDataUrl!=="string")return json({error:"Valid icon settings are required."},400);const result=await deps.create(account,workspaceId,{name:body.name,imageDataUrl:body.imageDataUrl});return result.kind==="limit"?json({status:"limit_reached",limit:result.limit},409):json({icon:result.icon},201)}}
const production={authenticate:authenticateActiveAccount,async authorize(account:Account,workspaceId:string){const db=getFirestore(getFirebaseAdminApp()),[workspace,membership]=await db.getAll(db.doc(`workspaces/${workspaceId}`),db.doc(`workspaceMemberships/${workspaceId}_${account.uid}`));const memberRole=membership.get("role");return workspace.exists&&workspace.get("status")==="active"&&membership.exists&&membership.get("status")==="active"&&role(memberRole)?{role:memberRole}:null},async list(_account:Account,workspaceId:string){const docs=await getFirestore(getFirebaseAdminApp()).collection(`workspaces/${workspaceId}/icons`).orderBy("updatedAt","desc").get();return docs.docs.flatMap((doc)=>{const item=summary(doc);return item?[item]:[]})},async create(account:Account,workspaceId:string,input:Input){const db=getFirestore(getFirebaseAdminApp()),workspace=db.doc(`workspaces/${workspaceId}`),membership=db.doc(`workspaceMemberships/${workspaceId}_${account.uid}`),icon=workspace.collection("icons").doc(),activity=workspace.collection("activity").doc();return db.runTransaction(async tx=>{const [ws,member]=await Promise.all([tx.get(workspace),tx.get(membership)]),memberRole=member.get("role");if(!ws.exists||ws.get("status")!=="active"||!member.exists||member.get("status")!=="active"||!role(memberRole)||memberRole==="viewer")throw new Error("Workspace editing access is unavailable.");const decision=decideIconCreation({iconCount:ws.get("iconCount")??0,requestedName:input.name,imageDataUrl:input.imageDataUrl});if(decision.kind==="limit")return decision;const now=FieldValue.serverTimestamp();tx.update(workspace,{iconCount:decision.nextIconCount,updatedAt:now});tx.set(icon,{name:decision.name,imageDataUrl:decision.imageDataUrl,status:"active",workspaceId,createdAt:now,createdBy:account.uid,updatedAt:now});tx.set(activity,{type:"icon.created",actorUid:account.uid,createdAt:now,resourceId:icon.id,resourceName:decision.name,resourceType:"icon",workspaceId});return {kind:"created" as const,icon:{id:icon.id,name:decision.name,imageDataUrl:decision.imageDataUrl}}})}};
const handler=createIconHandler(production);export default async function icons(request:Request){try{return await handler(request)}catch(error){console.error("Icon request failed.",error);return json({error:"Icon access is unavailable."},503)}}
