import { useState, type ChangeEvent, type FormEvent } from "react";
import { ICON_LIMIT } from "../../lib/icons/creation";
import type { WorkspaceRole } from "../../lib/workspaces/api-response";
import type { useIconLibrary } from "./use-icon-library";

function crop(file: File): Promise<string> {
  return new Promise((resolve, reject) => { const image = new Image(); image.onload = () => { const size = Math.min(image.width, image.height), sourceX = (image.width - size) / 2, sourceY = (image.height - size) / 2, canvas = document.createElement("canvas"); canvas.width = 512; canvas.height = 512; const context = canvas.getContext("2d"); if (!context) return reject(new Error()); context.drawImage(image, sourceX, sourceY, size, size, 0, 0, 512, 512); resolve(canvas.toDataURL("image/webp", 0.88)); }; image.onerror = () => reject(new Error()); image.src = URL.createObjectURL(file); });
}
export default function IconLibraryPage({ library, role }: { library: ReturnType<typeof useIconLibrary>; role: WorkspaceRole }) {
  const [open, setOpen] = useState(false), [name, setName] = useState(""), [image, setImage] = useState("");
  const canEdit = role !== "viewer";
  async function choose(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (file) setImage(await crop(file)); }
  async function submit(event: FormEvent) { event.preventDefault(); if (await library.create(name, image)) { setOpen(false); setName(""); setImage(""); } }
  return <><header className="workspace-page-heading deck-library-heading"><div><p className="workspace-kicker">Visual library</p><h1>Icons</h1><p>Upload and prepare reusable icons for QR codes.</p></div>{canEdit && <button onClick={() => setOpen(true)}>New icon <span>→</span></button>}</header><div className="deck-library-toolbar"><span>{library.icons.length} / {ICON_LIMIT} icons</span></div>{library.state === "loading" && <section className="deck-library-status"><p>Loading icons…</p></section>}{library.state === "error" && <section className="deck-library-status"><h2>We could not load your icons</h2><p>{library.error}</p></section>}{library.state === "ready" && library.icons.length === 0 && <section className="workspace-library-empty"><h2>No icons yet</h2><p>Upload an image and the reusable crop will be saved here.</p>{canEdit && <button className="deck-empty-action" onClick={() => setOpen(true)}>Add your first icon</button>}</section>}{library.icons.length > 0 && <section className="slide-card-grid">{library.icons.map(icon => <article className="slide-card" key={icon.id}><img className="icon-card-image" src={icon.imageDataUrl} alt="" /><h2>{icon.name}</h2></article>)}</section>}{open && <div className="deck-dialog-backdrop"><section className="deck-dialog" role="dialog" aria-modal="true"><button className="deck-dialog-close" onClick={() => setOpen(false)}>×</button><p className="workspace-kicker">Visual library</p><h2>Add an icon</h2><form onSubmit={submit}><label><span>Name</span><input value={name} onChange={event => setName(event.target.value)} autoFocus /></label><label><span>Image</span><input type="file" accept="image/png,image/jpeg,image/webp" onChange={choose} /></label>{image && <img className="icon-crop-preview" src={image} alt="Cropped icon preview" />}{library.error && <p className="auth-error">{library.error}</p>}<div><button type="button" onClick={() => setOpen(false)}>Cancel</button><button disabled={!name.trim() || !image}>Save icon</button></div></form></section></div>}</>;
}
