import { useMemo, useState } from "react";
import { ICON_LIMIT } from "../../lib/icons/creation";
import type { WorkspaceRole } from "../../lib/workspaces/api-response";
import type { useIconLibrary } from "./use-icon-library";

export default function IconLibraryPage({ library, role, onCreatePage }: { library: ReturnType<typeof useIconLibrary>; role: WorkspaceRole; onCreatePage: () => void }) {
  const [query, setQuery] = useState("");
  const canEdit = role !== "viewer";
  const icons = useMemo(() => { const term = query.trim().toLowerCase(); return term ? library.icons.filter((icon) => icon.name.toLowerCase().includes(term)) : library.icons; }, [library.icons, query]);
  return <><header className="workspace-page-heading deck-library-heading"><div><p className="workspace-kicker">Visual library</p><h1>Icons</h1><p>Upload and prepare reusable icons for QR codes.</p></div>{canEdit && <button type="button" onClick={onCreatePage}>New icon <span aria-hidden="true">→</span></button>}</header><div className="deck-library-toolbar"><label><span className="visually-hidden">Search icons</span><input type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search icons" /></label><span>{library.icons.length} / {ICON_LIMIT} icons</span></div>{library.state === "loading" && <section className="deck-library-status"><p>Loading icons…</p></section>}{library.state === "error" && <section className="deck-library-status"><h2>We could not load your icons</h2><p>{library.error}</p></section>}{library.state === "ready" && library.icons.length === 0 && <section className="workspace-library-empty"><span className="workspace-empty-mark deck-empty-mark">0</span><h2>No icons yet</h2><p>Upload an image and the reusable crop will be saved here.</p>{canEdit && <button className="deck-empty-action" type="button" onClick={onCreatePage}>Add your first icon</button>}</section>}{library.state === "ready" && library.icons.length > 0 && (icons.length === 0 ? <section className="deck-library-status"><h2>No matching icons</h2><p>Try a different search.</p></section> : <section className="slide-card-grid">{icons.map((icon) => <article className="slide-card" key={icon.id}><img className="icon-card-image" src={icon.imageDataUrl} alt="" /><h2>{icon.name}</h2></article>)}</section>)}</>;
}
