import type { User } from "firebase/auth";
import type { WorkspaceRole } from "../../lib/workspaces/api-response";

export type WorkspaceMember = { uid: string; role: WorkspaceRole; displayName: string | null; email: string | null };
const headers = async (user: User) => ({ authorization: `Bearer ${await user.getIdToken()}` });
const endpoint = (workspaceId: string, memberUid?: string) => `/api/workspaces/${encodeURIComponent(workspaceId)}/members${memberUid ? `/${encodeURIComponent(memberUid)}` : ""}`;
export async function requestMembers(user: User, workspaceId: string): Promise<WorkspaceMember[]> { const response = await fetch(endpoint(workspaceId), { headers: await headers(user) }); const body: unknown = await response.json().catch(() => null); if (response.ok && body && typeof body === "object" && "members" in body && Array.isArray(body.members)) return body.members as WorkspaceMember[]; throw new Error("QRousel could not load workspace members."); }
export async function updateMemberRole(user: User, workspaceId: string, memberUid: string, role: Exclude<WorkspaceRole, "founder">): Promise<void> { const response = await fetch(endpoint(workspaceId, memberUid), { method: "PATCH", headers: { ...(await headers(user)), "content-type": "application/json" }, body: JSON.stringify({ role }) }); if (!response.ok) { const body: unknown = await response.json().catch(() => null); throw new Error(body && typeof body === "object" && "error" in body && typeof body.error === "string" ? body.error : "QRousel could not change this member role."); } }
export async function revokeMember(user: User, workspaceId: string, memberUid: string): Promise<void> { const response = await fetch(endpoint(workspaceId, memberUid), { method: "DELETE", headers: await headers(user) }); if (!response.ok) throw new Error("QRousel could not remove this member."); }
export async function transferFounder(user: User, workspaceId: string, memberUid: string): Promise<void> { const response = await fetch(endpoint(workspaceId, memberUid), { method: "PATCH", headers: { ...(await headers(user)), "content-type": "application/json" }, body: JSON.stringify({ transferFounder: true }) }); if (!response.ok) throw new Error("QRousel could not transfer founder responsibility."); }
