import { useMemo, useState, type FormEvent } from "react";
import { type QrCodeKind } from "../../lib/qr-codes/creation";
import type { WorkspaceRole } from "../../lib/workspaces/api-response";
import type { useQrCodeLibrary } from "./use-qr-code-library";
import type { IconSummary } from "../../lib/icons/api-response";
import QrCodeCanvas from "./QrCodeCanvas";

function detect(value: string): QrCodeKind { if (/^https?:\/\//i.test(value)) return "url"; if (/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value)) return "email"; if (/^\+?[\d ()-]{7,}$/.test(value)) return "phone"; if (/^WIFI:/i.test(value)) return "wifi"; return "text"; }
function safety(scale: number) { return scale > .35 ? "Poor — may not scan" : scale > .28 ? "Fair — test before print" : "Excellent — safe"; }
export default function QrCodeCreatePage({ library, role, icons, onBack }: { library: ReturnType<typeof useQrCodeLibrary>; role: WorkspaceRole; icons: IconSummary[]; onBack: () => void }) {
  const [name, setName] = useState(""), [value, setValue] = useState(""), [kind, setKind] = useState<QrCodeKind>("url"), [color, setColor] = useState("#173D2C"), [version, setVersion] = useState(0), [iconId, setIconId] = useState(""), [logoScale, setLogoScale] = useState(.25);
  const icon = useMemo(() => icons.find((item) => item.id === iconId), [iconId, icons]);
  async function submit(event: FormEvent) { event.preventDefault(); if (await library.create({ name, kind, value, color, version, logoScale, iconId: iconId || null })) onBack(); }
  return <><button className="deck-editor-back" type="button" onClick={onBack}><span>←</span> QR codes</button><header className="deck-editor-heading"><div><span className="deck-status">new QR code</span><h1>Create a QR code</h1><p>Paste content, choose a reusable icon, then tune its scan-safe visual settings.</p></div></header><form className="deck-settings-card deck-create-page qr-editor-page" onSubmit={submit}><section className="qr-editor-preview"><QrCodeCanvas content={value || " "} color={color} version={version} logoScale={logoScale} iconImage={icon?.imageDataUrl} /><small>Live high-resolution preview</small></section><div className="qr-editor-fields"><label><span>Name</span><input autoFocus value={name} onChange={e => setName(e.target.value)} /></label><label><span>Content</span><input value={value} onChange={e => { setValue(e.target.value); setKind(detect(e.target.value)); }} placeholder="Paste a link, email, phone, Wi-Fi string, or text" /></label><label><span>Detected type</span><select value={kind} onChange={e => setKind(e.target.value as QrCodeKind)}>{["url", "email", "phone", "wifi", "text"].map(item => <option key={item}>{item}</option>)}</select></label><fieldset className="qr-icon-picker"><legend>Centre icon</legend><button className={!iconId ? "is-selected" : ""} type="button" onClick={() => setIconId("")}>No icon</button>{icons.map(item => <button className={item.id === iconId ? "is-selected" : ""} type="button" key={item.id} onClick={() => setIconId(item.id)}><img src={item.imageDataUrl} alt="" />{item.name}</button>)}</fieldset><label><span>Colour</span><div className="qr-colour-input"><input value={color} pattern="#[0-9A-Fa-f]{6}" onChange={e => setColor(e.target.value)} /><input type="color" value={color} onChange={e => setColor(e.target.value)} /></div></label><label><span>Grid density: {version === 0 ? "Auto" : `V${version}`}</span><input type="range" min="0" max="20" value={version} onChange={e => setVersion(Number(e.target.value))} /><small>Higher density gives a finer grid. If a selected version cannot hold the content, QRousel automatically uses the correct density.</small></label><label><span>Logo size: {Math.round(logoScale * 100)}%</span><input type="range" min="0.1" max="0.5" step="0.01" value={logoScale} disabled={!iconId} onChange={e => setLogoScale(Number(e.target.value))} /><small className={logoScale > .35 ? "qr-safety qr-safety-poor" : logoScale > .28 ? "qr-safety qr-safety-fair" : "qr-safety"}>{iconId ? safety(logoScale) : "Choose an icon to enable logo sizing."}</small></label></div>{library.error && <p className="auth-error">{library.error}</p>}<div className="deck-settings-actions"><button type="button" onClick={onBack}>Cancel</button><button disabled={role === "viewer" || !name.trim() || !value.trim()}>Create QR code</button></div></form></>;
}
