import { useState, type FormEvent } from "react";
import type { QrCodeSummary } from "../../lib/qr-codes/api-response";
import { type QrCodeKind } from "../../lib/qr-codes/creation";
import type { WorkspaceRole } from "../../lib/workspaces/api-response";
import type { useQrCodeLibrary } from "./use-qr-code-library";

function rawValue(code: QrCodeSummary) { return code.kind === "email" ? code.content.replace(/^mailto:/, "") : code.kind === "phone" ? code.content.replace(/^tel:/, "") : code.content; }
export default function QrCodeEditPage({ library, role, code, onBack }: { library: ReturnType<typeof useQrCodeLibrary>; role: WorkspaceRole; code: QrCodeSummary; onBack: () => void }) {
  const [name, setName] = useState(code.name), [value, setValue] = useState(rawValue(code)), [kind, setKind] = useState<QrCodeKind>(code.kind), [color, setColor] = useState(code.color), [version, setVersion] = useState(code.version), [conflict, setConflict] = useState<QrCodeSummary | null>(null);
  async function submit(event: FormEvent) { event.preventDefault(); const result = await library.update(code, { name, value, kind, color, version }); if (result?.kind === "updated") onBack(); if (result?.kind === "conflict") setConflict(result.qrCode); }
  return <><button className="deck-editor-back" type="button" onClick={onBack}><span>←</span> QR codes</button><header className="deck-editor-heading"><div><span className="deck-status">reusable QR code</span><h1>Edit QR code</h1><p>Update content, type, colour, and density. Every linked slide will use the updated design.</p></div></header>{conflict && <section className="deck-conflict" role="alert"><p className="workspace-kicker">Changed elsewhere</p><h2>This QR code was updated after you opened it</h2><div className="deck-conflict-actions"><button type="button" onClick={() => { setName(conflict.name); setValue(rawValue(conflict)); setKind(conflict.kind); setColor(conflict.color); setVersion(conflict.version); setConflict(null); }}>Reload latest</button><button type="button" onClick={onBack}>Cancel</button></div></section>}<form className="deck-settings-card deck-create-page" onSubmit={submit}><label><span>Name</span><input autoFocus value={name} onChange={(event) => setName(event.target.value)} /></label><label><span>Content</span><input value={value} onChange={(event) => setValue(event.target.value)} /></label><label><span>Content type</span><select value={kind} onChange={(event) => setKind(event.target.value as QrCodeKind)}>{["url", "email", "phone", "wifi", "text"].map((item) => <option key={item}>{item}</option>)}</select></label><label><span>Colour</span><input value={color} pattern="#[0-9A-Fa-f]{6}" onChange={(event) => setColor(event.target.value)} /><input type="color" value={color} onChange={(event) => setColor(event.target.value)} /></label><label><span>Density: {version === 0 ? "Auto" : version}</span><input type="range" min="0" max="20" value={version} onChange={(event) => setVersion(Number(event.target.value))} /></label>{library.error && <p className="auth-error">{library.error}</p>}<div className="deck-settings-actions"><button type="button" onClick={onBack}>Cancel</button><button disabled={role === "viewer" || !name.trim() || !value.trim()}>Save QR code</button></div></form></>;
}
