import { useEffect, useRef } from "react";

type QrLibrary = { (version: number, correction: "H"): { addData(value: string): void; make(): void; getModuleCount(): number; isDark(row: number, column: number): boolean; }; };
declare global { interface Window { qrcode?: QrLibrary; } }
let loader: Promise<void> | null = null;
function loadQrLibrary(): Promise<void> { if (window.qrcode) return Promise.resolve(); if (loader) return loader; loader = new Promise((resolve, reject) => { const script = document.createElement("script"); script.src = "https://cdnjs.cloudflare.com/ajax/libs/qrcode-generator/1.4.4/qrcode.min.js"; script.onload = () => resolve(); script.onerror = () => reject(new Error("QR code renderer could not load.")); document.head.append(script); }); return loader; }
function round(context: CanvasRenderingContext2D, x: number, y: number, size: number, radius: number) { context.beginPath(); context.roundRect(x, y, size, size, radius); context.fill(); }

export default function QrCodeCanvas({ content, color, version, logoScale = 0.25, iconImage }: { content: string; color: string; version: number; logoScale?: number; iconImage?: string }) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  useEffect(() => { let active = true; void loadQrLibrary().then(() => { if (!active || !canvasRef.current || !window.qrcode) return; let qr; try { qr = window.qrcode(version, "H"); qr.addData(content || " "); qr.make(); } catch { qr = window.qrcode(0, "H"); qr.addData(content || " "); qr.make(); }
    const modules = qr.getModuleCount(), padding = 2, unit = Math.max(10, Math.ceil(1024 / (modules + padding * 2))), size = (modules + padding * 2) * unit, canvas = canvasRef.current, context = canvas.getContext("2d"); if (!context) return; const drawingContext = context; canvas.width = size; canvas.height = size; drawingContext.fillStyle = "#FFFFFF"; drawingContext.fillRect(0, 0, size, size);
    const logoModules = iconImage ? Math.floor(modules * logoScale) : 0, logoStart = Math.floor((modules - logoModules) / 2), logoEnd = logoStart + logoModules, isEye = (row: number, column: number) => (row < 7 && column < 7) || (row < 7 && column >= modules - 7) || (row >= modules - 7 && column < 7), isLogo = (row: number, column: number) => iconImage && row >= logoStart && row < logoEnd && column >= logoStart && column < logoEnd;
    drawingContext.fillStyle = color; for (let row = 0; row < modules; row += 1) for (let column = 0; column < modules; column += 1) if (!isEye(row, column) && !isLogo(row, column) && qr.isDark(row, column)) drawingContext.fillRect((column + padding) * unit, (row + padding) * unit, unit + 0.5, unit + 0.5);
    function eye(row: number, column: number) { const x = (column + padding) * unit, y = (row + padding) * unit, outer = unit * 7, border = unit, radius = Math.max(2, outer * 0.22); drawingContext.fillStyle = color; round(drawingContext, x, y, outer, radius); drawingContext.fillStyle = "#FFFFFF"; round(drawingContext, x + border, y + border, outer - border * 2, radius * 0.6); drawingContext.fillStyle = color; round(drawingContext, x + border * 2, y + border * 2, outer - border * 4, radius * 0.35); }
    eye(0, 0); eye(0, modules - 7); eye(modules - 7, 0);
    if (iconImage) { const icon = new Image(); icon.onload = () => { if (!active) return; const area = logoModules * unit, x = (logoStart + padding) * unit, y = (logoStart + padding) * unit, border = unit * 0.65, radius = Math.max(unit, area * 0.14); drawingContext.fillStyle = "#FFFFFF"; round(drawingContext, x - border, y - border, area + border * 2, radius); const ratio = icon.width / icon.height, drawWidth = ratio > 1 ? area : area * ratio, drawHeight = ratio > 1 ? area / ratio : area; drawingContext.save(); drawingContext.beginPath(); drawingContext.roundRect(x + (area - drawWidth) / 2, y + (area - drawHeight) / 2, drawWidth, drawHeight, radius * 0.6); drawingContext.clip(); drawingContext.drawImage(icon, x + (area - drawWidth) / 2, y + (area - drawHeight) / 2, drawWidth, drawHeight); drawingContext.restore(); }; icon.src = iconImage; }
  }); return () => { active = false; }; }, [color, content, iconImage, logoScale, version]);
  return <canvas className="qr-code-canvas" ref={canvasRef} aria-label="QR code preview" />;
}
